# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PartTime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PartTime
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'SVProgressHUD'
  pod 'ReactiveCocoa', '~> 2.3.1'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'Masonry'


end
